apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: ollama-example
  annotations:
    version: v0.0.1
    description: "Simple ollama example"
spec:
  components:
    - name: http-component
      type: component
      properties:
        image: file://./build/ollama_example_s.wasm
      traits:
        # Govern the spread/scheduling of the component
        - type: spreadscaler
          properties:
            replicas: 1
        - type: link
          properties:
            target: ollama
            namespace: thomastaylor312
            package: ollama
            interfaces: [generate]
            target_config:
              - name: ollama-conf
                properties:
                  model_name: llama3:8b-instruct-fp16

    # Add a capability provider that enables HTTP access
    - name: httpserver
      type: capability
      properties:
        image: ghcr.io/wasmcloud/http-server:0.20.0
      traits:
        # Link the httpserver to the component, and configure the HTTP server
        # to listen on port 8080 for incoming requests
        - type: link
          properties:
            target: http-component
            namespace: wasi
            package: http
            interfaces: [incoming-handler]
            source_config:
              - name: default-http
                properties:
                  address: 127.0.0.1:8080

    - name: ollama
      type: capability
      properties:
        image: file://../build/ollama-provider.par.gz
